### ISSUE TITLE
Walled template causes overhead tiles to appear under tokens

### ISSUE THREAD

**Issue by morepurplemorebetter** [caewok/fvtt-walled-templates#62] opened 2023-09-12 19:16 UTC
I am not sure what is causing this issue, but when I turn off the Walled Template module, the problem disappears. While Walled Templates is active in my world, overhead tiles are rendered underneath tokens.

**Comment by morepurplemorebetter** [comment] 2023-09-13 07:36
Testing this on a fresh world, with no other modules active, I see that this issue isn't caused by Walled Templates (alone). The issue shows itself when I activate both the "Walled Templates" and the ["Better Roofs" module](https://github.com/theripper93/Better-Roofs) (and nothing else).

Perhaps you can fix the problem or include an incompatibility warning in the readme.

**Comment by morepurplemorebetter** [comment] 2023-09-13 08:42
Correction to my previous comment: There are no other modules (or module-interactions) causing this issue, it is solely caused by Walled Templates. You just need to refresh the page before it becomes visible with tiles you added/edited during the current browser session.

&nbsp;

**How to test:**
1. Start a fresh world
2. Enable Walled Templates (and libWrapper)
3. Edit a tile to be overhead (or add a new tile and make it overhead)
4. Add a token and put it "under" this overhead tile
5. Refresh the page
6. See that the token is now standing on top of the overhead tile

&nbsp;

**Tested with:**
- FoundryVTT v11.307
- Walled Templates v0.6.6, v0.6.7, and v0.6.8

**Comment by caewok** [comment] 2023-09-14 13:21
Thanks for the careful writeup! Fixed in v0.6.9. 

(The issue is related to some weirdness in how Foundry v11 treats tile elevation—it is a document property but not really. Walled Templates doesn't need to mess with tile elevation, but for compatibility with Elevated Vision it shares some code that I tweaked to hopefully fix the issue.)

**Closed by caewok** 2023-09-14 13:21 UTC
